name: CI Tests

on:
  push:
    branches:
    - master
  #  tags: # run CI if specific tags are pushed
  pull_request:
    branches:
      - master

jobs:
  # Github Actions supports ubuntu, windows, and macos virtual environments:
  # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
  ci_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Ubuntu - Python 3.11 with all optional dependencies
            os: ubuntu-latest
            python: "3.11"
            toxenv: 'py11-test-alldeps'

          - name: MacOs - Python 3.11 with all optional dependencies
            os: macos-latest
            python: "3.11"
            toxenv: 'py11-test-alldeps'

          - name: Ubuntu - Python 3.12 with all optional dependencies
            os: ubuntu-latest
            python: "3.12"
            toxenv: 'py312-test-alldeps'

          - name: MacOs - Python 3.12 with all optional dependencies
            os: macos-latest
            python: "3.12"
            toxenv: 'py312-test-alldeps'

          - name: Ubuntu - Python 3.13 with all optional dependencies
            os: ubuntu-latest
            python: "3.13"
            toxenv: 'py313-test-alldeps'

          - name: MacOs - Python 3.13 with all optional dependencies
            os: macos-latest
            python: "3.13"
            toxenv: 'py313-test-alldeps'

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0
    - name: Set up python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox codecov
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}
    # This is an example of how to upload coverage to codecov
    # - name: Upload coverage to codecov
    #   if: "contains(matrix.toxenv, '-cov')"
    #   uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673  # v4.5.0
    #   with:
    #     file: ./coverage.xml
