name: Cron Tests

on:
  workflow_dispatch: null
  schedule:
    # Runs "First of every month at 3:15am Central"
    - cron: '15 8 1 * *'

jobs:
  # Github Actions supports ubuntu, windows, and macos virtual environments:
  # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
  ci_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Ubuntu - Python 3.10 with all optional dependencies
            os: ubuntu-latest
            python: "3.10"
            toxenv: 'py10-test-alldeps'

          - name: MacOs - Python 3.10 with all optional dependencies
            os: macos-latest
            python: "3.10"
            toxenv: 'py10-test-alldeps'

          - name: Ubuntu - Python 3.11 with all optional dependencies
            os: ubuntu-latest
            python: "3.11"
            toxenv: 'py11-test-alldeps'

          - name: MacOs - Python 3.11 with all optional dependencies
            os: macos-latest
            python: "3.11"
            toxenv: 'py11-test-alldeps'

          - name: Ubuntu - Python 3.12 with all optional dependencies
            os: ubuntu-latest
            python: "3.12"
            toxenv: 'py312-test-alldeps'

          - name: MacOs - Python 3.12 with all optional dependencies
            os: macos-latest
            python: "3.12"
            toxenv: 'py312-test-alldeps'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox codecov
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}
